//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Point_of_Sale_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public string id { get; set; }
        public string barcode { get; set; }
        public Nullable<int> cat_id { get; set; }
        public Nullable<int> brand_id { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<int> price { get; set; }
    }
}
